src/main/java/com/sparta/tl3p/backend/BackendApplication.java, src/main/java/com/sparta/tl3p/backend/common/audit/BaseEntity.java, src/main/java/com/sparta/tl3p/backend/domain/order/entity/Order.java
- Order 초기 파일을 생성하였습니다.
1.  Order.java 파일 생성.
- domain - order - entity 아래에 설정.
=> init: 초기 파일 생성

src/main/java/com/sparta/tl3p/backend/common/dto/ErrorResponseDto.java, src/main/java/com/sparta/tl3p/backend/common/dto/SuccessResponseDto.java, src/main/java/com/sparta/tl3p/backend/common/exception/BusinessException.java, src/main/java/com/sparta/tl3p/backend/common/handler/GlobalExceptionHandler.java, src/main/java/com/sparta/tl3p/backend/common/type/ErrorCode.java, src/main/java/com/sparta/tl3p/backend/common/type/ResponseCode.java
1. 공통 Response 클래스
2. 글로벌 예외 핸들러
3. 비즈니스 예외 클래스 및 ENUM type 코드 구성
브랜치명 오타.. exeption -> exception 으로 정정..
=> [공통 기능 구현]

build.gradle, src/main/java/com/sparta/tl3p/backend/domain/store/dto/StoreRequestDto.java, src/main/java/com/sparta/tl3p/backend/domain/store/dto/StoreResponseDto.java, src/main/java/com/sparta/tl3p/backend/domain/store/entity/Store.java, src/main/java/com/sparta/tl3p/backend/domain/store/entity/StoreCategory.java, src/main/java/com/sparta/tl3p/backend/domain/store/enums/CategoryType.java, src/main/java/com/sparta/tl3p/backend/domain/store/enums/StoreStatus.java
=> [Base Entity 활용]

src/main/java/com/sparta/tl3p/backend/common/config/QueryDslConfig.java, src/main/java/com/sparta/tl3p/backend/common/type/ErrorCode.java, src/main/java/com/sparta/tl3p/backend/domain/item/entity/Item.java, src/main/java/com/sparta/tl3p/backend/domain/member/entity/Member.java, src/main/java/com/sparta/tl3p/backend/domain/order/entity/Order.java, src/main/java/com/sparta/tl3p/backend/domain/order/entity/OrderItem.java, src/main/java/com/sparta/tl3p/backend/domain/payment/entity/Payment.java, src/main/java/com/sparta/tl3p/backend/domain/review/controller/ReviewController.java, src/main/java/com/sparta/tl3p/backend/domain/review/dto/ReviewCreationRequestDto.java, src/main/java/com/sparta/tl3p/backend/domain/review/dto/ReviewResponseDto.java, src/main/java/com/sparta/tl3p/backend/domain/review/dto/ReviewUpdateRequestDto.java, src/main/java/com/sparta/tl3p/backend/domain/review/entity/Review.java, src/main/java/com/sparta/tl3p/backend/domain/review/repository/ReviewRepository.java, src/main/java/com/sparta/tl3p/backend/domain/review/service/ReviewService.java
api controller, ReviewService 개발, entity 수정
ReviewRepository 개발(ing)
todo: queryDSL 적용 & repository 지연로딩 처리
=> [feature/review] review 도메인 개발

build.gradle, src/main/java/com/sparta/tl3p/backend/domain/member/config/SecurityConfig.java, src/main/java/com/sparta/tl3p/backend/domain/member/controller/MemberController.java, src/main/java/com/sparta/tl3p/backend/domain/member/dto/MemberRequestDto.java, src/main/java/com/sparta/tl3p/backend/domain/member/dto/MemberResponseDto.java, src/main/java/com/sparta/tl3p/backend/domain/member/entity/Member.java, src/main/java/com/sparta/tl3p/backend/domain/member/enums/MemberStatus.java, src/main/java/com/sparta/tl3p/backend/domain/member/enums/Role.java, src/main/java/com/sparta/tl3p/backend/domain/member/repository/MemberRepository.java, src/main/java/com/sparta/tl3p/backend/domain/member/service/MemberService.java, src/main/java/com/sparta/tl3p/backend/domain/order/entity/Order.java, src/main/java/com/sparta/tl3p/backend/domain/order/entity/OrderItem.java
=> feat: 회원가입 및 회원조회

src/main/java/com/sparta/tl3p/backend/domain/review/entity/Review.java
Review Entity @Id 칼럼 타입 변경 (Long -> UUID)
발견 못 해서 죄송해요...😳 merge 하면 런타임에러 사라집니다
=> [hotfix/review-entity]

src/main/java/com/sparta/tl3p/backend/common/type/ErrorCode.java, src/main/java/com/sparta/tl3p/backend/domain/store/controller/StoreController.java, src/main/java/com/sparta/tl3p/backend/domain/store/dto/StoreResponseDto.java, src/main/java/com/sparta/tl3p/backend/domain/store/entity/Store.java, src/main/java/com/sparta/tl3p/backend/domain/store/repository/StoreCategoryRepository.java, src/main/java/com/sparta/tl3p/backend/domain/store/repository/StoreRepository.java, src/main/java/com/sparta/tl3p/backend/domain/store/service/StoreService.java
Store
- Controller
- Service
- Repository
구현 완료
=> [init / Stores - CSR]

src/main/java/com/sparta/tl3p/backend/domain/store/controller/StoreController.java, src/main/java/com/sparta/tl3p/backend/domain/store/dto/StoreRequestDto.java, src/main/java/com/sparta/tl3p/backend/domain/store/dto/StoreResponseDto.java, src/main/java/com/sparta/tl3p/backend/domain/store/entity/Store.java, src/main/java/com/sparta/tl3p/backend/domain/store/repository/StoreRepository.java, src/main/java/com/sparta/tl3p/backend/domain/store/service/StoreService.java
=> [fix / Store - member]

src/main/java/com/sparta/tl3p/backend/common/type/Address.java, src/main/java/com/sparta/tl3p/backend/domain/item/dto/ItemResponseDto.java, src/main/java/com/sparta/tl3p/backend/domain/member/dto/MemberRequestDto.java, src/main/java/com/sparta/tl3p/backend/domain/member/dto/MemberResponseDto.java, src/main/java/com/sparta/tl3p/backend/domain/member/entity/Member.java, src/main/java/com/sparta/tl3p/backend/domain/order/dto/OrderDetailResponseDto.java, src/main/java/com/sparta/tl3p/backend/domain/order/dto/OrderRequestDto.java, src/main/java/com/sparta/tl3p/backend/domain/order/dto/OrderResponseDto.java, src/main/java/com/sparta/tl3p/backend/domain/order/dto/StoreOrderListItemDto.java, src/main/java/com/sparta/tl3p/backend/domain/order/dto/UserOrderListItemDto.java, src/main/java/com/sparta/tl3p/backend/domain/order/entity/Order.java, src/main/java/com/sparta/tl3p/backend/domain/order/service/OrderService.java, src/main/java/com/sparta/tl3p/backend/domain/store/dto/StoreRequestDto.java, src/main/java/com/sparta/tl3p/backend/domain/store/dto/StoreResponseDto.java, src/main/java/com/sparta/tl3p/backend/domain/store/entity/Store.java, src/main/java/com/sparta/tl3p/backend/domain/store/repository/StoreCategoryRepository.java, src/main/java/com/sparta/tl3p/backend/domain/store/repository/StoreRepository.java, src/main/java/com/sparta/tl3p/backend/domain/store/service/StoreService.java
엔티티 규칙 통일 위해 Store 엔티티 id 필드명 변경. (id -> storeId)
Member 엔티티 owner 필드 제거
StoreRepository, StoreCategoryRepository QueryMethod 오류로 수정
StoreService에 기존 storeId와 memberId로 조회하던 store 조회 메서드를 findById(storeId) 로 수정
=> [hoxfix] develop 브랜치 merge 후 에러 처리

src/main/java/com/sparta/tl3p/backend/common/type/ErrorCode.java, src/main/java/com/sparta/tl3p/backend/domain/member/controller/MemberController.java, src/main/java/com/sparta/tl3p/backend/domain/member/dto/MemberRequestDto.java, src/main/java/com/sparta/tl3p/backend/domain/member/service/MemberService.java, src/main/java/com/sparta/tl3p/backend/domain/review/entity/Review.java
errorCode 추가 
회원가입, 회원조회, 수정, 삭제 기능 구현
비즈니스 예외로 수정
=> feat : member 

build.gradle, src/main/java/com/sparta/tl3p/backend/domain/store/dto/StoreRequestDto.java, src/main/java/com/sparta/tl3p/backend/domain/store/dto/StoreResponseDto.java, src/test/java/com/sparta/tl3p/backend/store/StoreServiceTest.java
=> [init / Stores - UnitTest] 

src/main/java/com/sparta/tl3p/backend/domain/item/dto/ItemResponseDto.java, src/main/java/com/sparta/tl3p/backend/domain/item/entity/Item.java, src/main/java/com/sparta/tl3p/backend/domain/order/dto/OrderItemDetailDto.java, src/main/java/com/sparta/tl3p/backend/domain/review/controller/ReviewController.java, src/main/java/com/sparta/tl3p/backend/domain/review/controller/ReviewOwnerController.java, src/main/java/com/sparta/tl3p/backend/domain/review/dto/ReviewItemResponseDto.java, src/main/java/com/sparta/tl3p/backend/domain/review/dto/ReviewResponseDto.java, src/main/java/com/sparta/tl3p/backend/domain/review/repository/ReviewCustomRepository.java, src/main/java/com/sparta/tl3p/backend/domain/review/repository/ReviewCustomRepositoryImpl.java, src/main/java/com/sparta/tl3p/backend/domain/review/repository/ReviewRepository.java, src/main/java/com/sparta/tl3p/backend/domain/review/service/ReviewService.java
#특이사항
Item 엔티티 필드명 id -> itemId로 수정
#구현사항
리뷰 관련 검색 기능, owner 기능 구현 (QueryDSL 적용)
=> [Feature/review search]

src/main/java/com/sparta/tl3p/backend/common/type/Address.java, src/main/java/com/sparta/tl3p/backend/common/type/ErrorCode.java, src/main/java/com/sparta/tl3p/backend/domain/order/dto/OrderDetailResponseDto.java, src/main/java/com/sparta/tl3p/backend/domain/order/dto/OrderRequestDto.java, src/main/java/com/sparta/tl3p/backend/domain/order/dto/OrderResponseDto.java, src/main/java/com/sparta/tl3p/backend/domain/order/entity/Order.java, src/main/java/com/sparta/tl3p/backend/domain/review/entity/Review.java, src/main/java/com/sparta/tl3p/backend/domain/review/repository/ReviewCustomRepositoryImpl.java, src/main/java/com/sparta/tl3p/backend/domain/review/repository/ReviewRepository.java, src/main/java/com/sparta/tl3p/backend/domain/review/service/ReviewService.java, src/test/java/com/sparta/tl3p/backend/review/ReviewServiceTest.java
#변경사항
리뷰 조회 로직에 deleted 확인 로직 추가
Order - Review 양방향 일대일관계로 되어 있는 거 확인 -> review 추가할 때 order 쪽에도 review  추가하도록 createReview 메서드를 수정했는데 뭔가 이상한 것 같아요 로직이
#구현사항
리뷰 서비스 단위 테스트
=> [Feature/review-unit-test]

build.gradle, src/main/java/com/sparta/tl3p/backend/common/config/ApiConfig.java, src/main/java/com/sparta/tl3p/backend/domain/store/dto/StoreRequestDto.java
=> [init / ApiConfig, Dotenv]

src/main/java/com/sparta/tl3p/backend/common/type/ErrorCode.java, src/main/java/com/sparta/tl3p/backend/domain/order/controller/OrderController.java, src/main/java/com/sparta/tl3p/backend/domain/order/service/OrderService.java
권한 설정 추가 했고, 
서비스 코드에서 5분 이내 주문 취소 가능한 내용 추가.
=> refactor : 권한 설정 추가, 5분 이내 주문만 취소, 수정 가능하도록 추가

Dockerfile, Jenkinsfile
add Dockerfile
modify Jenkinsfile for application.yml
=> Dockerfile, Jenkinsfile application.yml

src/main/java/com/sparta/tl3p/backend/domain/order/controller/OrderController.java, src/main/java/com/sparta/tl3p/backend/domain/order/entity/OrderItem.java, src/test/java/com/sparta/tl3p/backend/order/OrderServiceTest.java
=> refactor: 코드 수정 및 테스트 코드추가

src/main/java/com/sparta/tl3p/backend/common/config/SecurityConfig.java, src/main/java/com/sparta/tl3p/backend/common/type/ErrorCode.java, src/main/java/com/sparta/tl3p/backend/domain/store/controller/StoreController.java, src/main/java/com/sparta/tl3p/backend/domain/store/dto/StoreRequestDto.java, src/main/java/com/sparta/tl3p/backend/domain/store/dto/StoreResponseDto.java, src/main/java/com/sparta/tl3p/backend/domain/store/entity/Store.java, src/main/java/com/sparta/tl3p/backend/domain/store/entity/StoreCategory.java, src/main/java/com/sparta/tl3p/backend/domain/store/repository/StoreCategoryRepository.java, src/main/java/com/sparta/tl3p/backend/domain/store/repository/StoreRepository.java, src/main/java/com/sparta/tl3p/backend/domain/store/service/StoreService.java, src/test/java/com/sparta/tl3p/backend/store/StoreServiceTest.java
=> [hotfix: store/category]

src/main/java/com/sparta/tl3p/backend/domain/store/repository/StoreCategoryRepository.java, src/test/java/com/sparta/tl3p/backend/store/StoreServiceTest.java
=> [hotfix: storeTest]

src/test/java/com/sparta/tl3p/backend/order/OrderServiceTest.java
=> test: orderTest 코드 수정
